blank_issues_enabled: false
contact_links:
  - name: Polypheny Community Support
    url: https://github.com/polypheny/Polypheny-DB/discussions
    about: If you have a question, or are looking for advice, please post on our Discussion page! The community loves to chime in to help.
